### ISSUE TITLE
Schema Marking Property of a $ref as Required Results in oas-schema-check Error

### ISSUE THREAD

**Issue by sshaw** [daveshanley/vacuum#566] opened 2024-10-08 18:47 UTC
Using 0.13.5 with the following: 

```yml
# ...

schema_a:
  type: object
  properties:
    schema_a_foo:
      type: string

schema_b:
  allOf:
    - $ref: '#/components/schemas/schema_a'
    - type: object
      required:
        - schema_a_foo
        - foo
      properties:
        foo:
          type: string
        bar:
          type: string
```

Results in an error for `schema_a_foo`: 

```
`required` field `schema_a_foo` is not defined in `properties`
```

Is this is correct? We've been using it for sometime without issue and I do see ~it~ in Swagger's editor `schema_a_foo` being marked as required 😅

**Comment by LasneF** [comment] 2024-10-09 09:37
@sshaw , your structure is correct , it impose that any object of following schema_b must havea shema_a_foo field and that it is a string 

the issue you are raising is a duplicate of this one 
https://github.com/daveshanley/vacuum/issues/468 

@daveshanley  you might close it

**Comment by daveshanley** [comment] 2024-11-21 16:08
Yeah this OK - if you see the enhancement (https://github.com/daveshanley/vacuum/issues/468) the rule needs to be upgraded to look down polymorphic objects for required props. 

You can ignore this for your own design.

**Closed by daveshanley** 2024-11-21 16:08 UTC
